

import prod1 from "../../../assets/grocery/prod1.png";
import prod2 from "../../../assets/grocery/prod2.png";
import prod3 from "../../../assets/grocery/prod3.png";
import prod4 from "../../../assets/grocery/prod4.png";
import prod5 from "../../../assets/grocery/prod5.png";
import prod6 from "../../../assets/grocery/prod6.png";
import cart from "../../../assets/grocery/cart.png";
import Addicon from "../../../assets/grocery/Addicon.png"
export const productList = [
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    style: {},
  },
  {
    img: prod4,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod5,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod6,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod4,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod5,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod6,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    style: {},
  },
  {
    img: prod4,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod5,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod6,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod4,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod5,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod6,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    style: {},
  },
  {
    img: prod4,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod5,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod6,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod4,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod5,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod6,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    style: {},
  },
  {
    img: prod4,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod5,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod6,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod4,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod5,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart:cart,
    Addicon:Addicon,
    style: {}
  },
  {
    img: prod6,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod1,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod2,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    Addicon:Addicon,
    style: {},
  },
  {
    img: prod3,
    title: "Parachute Pure Edible Beetroot",
    currency: "AED",
    price: "30.00",
    cart: cart,
    style: {},
  },
  
];
